### ISSUE TITLE
Add sorting functionality

### ISSUE THREAD

**Issue by Vercryger** [QActivo/meteor-tables#4]
Expected behavior and, look and feel:

![screen shot 2016-10-14 at 2 43 22 pm](https://cloud.githubusercontent.com/assets/3949146/19397076/a2dd47ec-921c-11e6-85a2-53d01809a297.png)

**Comment by yrahul3910** [comment]
Sorting functionality to what?

**Comment by nistath** [comment]
How do you store the data in the table? Point me to the method that defines a table and I'll do this quick.

**Comment by Vercryger** [comment]
@nistath Please, see README.
